### ISSUE TITLE
Corrupted Backups

### ISSUE THREAD

**Issue by davestgermain** [nathan-osman/django-archive#8]
The tar file [isn't closed](https://github.com/nathan-osman/django-archive/blob/master/django_archive/management/commands/archive.py#L55), resulting in corrupted backups. Either call `tar.close()` or, better yet, do all of the operations inside a `with` block.

**Comment by davestgermain** [comment]
@nathan-osman can you release the latest code to pypi, fixing #7?

**Comment by nathan-osman** [comment]
Sure! django-archive 0.1.6 is now live.
